plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com'
version = '0.0.1-SNAPSHOT'
description = 'msa4-meerkatgram-v2-auth'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
//    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    // OAuth2
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // jjwt
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // JPA & QueryDSL(** 현재는 학습내용과 상이하지 않도록 5.x를 사용하나, 실무에서는 6.x 버전으로 마이그레이션 필요 **)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:5.1.0:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    // SpringDoc Openapi (Swagger)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    // Lombok
    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // Configuration
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // Minio SDK
    implementation "io.minio:minio:8.6.0"

    // DB
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Kafka
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    // junit
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

import java.nio.file.Files
import java.nio.file.Paths
tasks.named('test') {
    useJUnitPlatform()

    // 테스트 실행 전 프로젝트 루트의 .env 파일을 읽어 System Property로 주입
    def envFile = Paths.get(project.rootDir.absolutePath, '.env')
    if (Files.exists(envFile)) {
        Files.readAllLines(envFile).each { line ->
            // 주석(#)이나 빈 줄 제외, 'KEY=VALUE' 형태만 파싱
            if (line.trim() && !line.startsWith('#') && line.contains('=')) {
                def (key, value) = line.split('=', 2).collect { it.trim() }
                // 따옴표가 포함되어 있다면 제거
                value = value.replaceAll(/^["']|["']$/, '')
                systemProperty key, value
            }
        }
    }
}
